---
#引入PHP运行环境元数据，并初始化
- include_vars: roles/role_php/vars/php_runtime_meta.yml

#Create var for this playbook
- set_fact:
    zentao_vhost_dir: "{{php_runtime_meta[ansible_os_family][zentao_webs].vhost_dir}}"
    zentao_vhost_src: "{{php_runtime_meta[ansible_os_family][zentao_webs].vhost_src}}"
    zentao_service: "{{php_runtime_meta[ansible_os_family][zentao_webs].service}}"
    zentao_owner: "{{php_runtime_meta[ansible_os_family][zentao_webs].owner}}"
    zentao_db_password: "{{mysql_root_password}}"

- debug:
    msg: runtime {{ zentao_vhost_dir }}, {{zentao_vhost_src}}, {{zentao_service}}, {{zentao_owner}}, {{zentao_webs}}, {{ansible_distribution}}

# ZenTao
- name: Remove extra dir
  shell: rm -rf /data/wwwroot/{{zentao_name}}

- name: Download ZenTaoPMS from {{zentao_download_url_meta[zentao_distribution].url}}
  unarchive:
    src: "{{zentao_download_url_meta[zentao_distribution].url}}"
    dest: /data/wwwroot
    remote_src: yes

- name: Rename dir name
  shell: cd /data/wwwroot; if [ ! -d "{{zentao_name}}" ]; then mv *{{zentao_name}}* {{zentao_name}}; fi

- name: Delete .htaccess .ztaccess
  file: 
    path: "{{item}}"
    state: absent
  with_items:
    - /data/wwwroot/zentao/www/.htaccess
    - /data/wwwroot/zentao/www/.ztaccess

# 系统通用
- name: Permission directory & file 
  shell: |
    find /data/wwwroot -type d -exec chmod 750 {} \;
    find /data/wwwroot -not -type d -exec chmod 640 {} \;
    # find /data/wwwroot/zentao/www/data -type d -exec chmod 750 {} \;
    
# 根据不同的基础环境分别处理
- block:
  - name: change owner&group
    shell: chown -R {{zentao_owner}}:{{zentao_owner}} /data/wwwroot

  - name: Copy Apache or Nginx vhost configuration
    template: src={{zentao_vhost_src}} dest={{zentao_vhost_dir}}
    
  - name: restart Apache or Nginx
    service: name={{zentao_service}} state=restarted enabled=yes

  - name: restart php-fpm
    service: name=php-fpm state=restarted

# Check zootao version
- name: Check joomla version
  shell: >
    sudo echo "zootao version:" $(cat /data/wwwroot/zentao/VERSION) |tee -a /data/logs/install_version.txt
